### ISSUE TITLE
Transitions slide into bottom-right

### ISSUE THREAD

**Issue by seagull** [07151129/sh3proxy#15] opened 2016-11-26 02:28 UTC
First of all, amazing work. It runs like an HD remaster.
The only issue that I'm having trouble with is that transitions – starting with the Konami logo, but everything from map screens to the pause menu – "slide" about 20 pixels into the lower-right when fading out.
It's a difficult thing to describe past that; I can provide videos if you need.

OS: Windows 10 1607 x64 Enterprise
CPU: Intel i5-2500k
GPU: GeForce 770
Res: 1920x1200 (primary)

**Comment by 07151129** [comment] 2016-12-03 22:11
Is the problem similar to one described in #14?

**Comment by seagull** [comment] 2016-12-04 02:59
I don't believe so. My EXE CRC32 is 372AE792.
Here's what I'm seeing: https://my.mixtape.moe/kkdkeo.webm
Here's my INI: http://pastebin.com/GnkQjRPm
I wonder if it isn't my 1920x1200 resolution that's causing issues?

**Comment by JoesGuy** [comment] 2017-07-18 05:28
I can confirm that this drifting transition bug occurs no matter the resolution. Still tweaking options, but no results yet.

**Comment by Zerobinary99** [comment] 2017-07-21 04:44
I'm experiencing the same issue.

**Comment by TaiNoBouken** [comment] 2017-07-23 16:49
Has anyone tried on a 32-bit OS? On my old rig I used D3DOverrider to fix some screen tearing and had no issues but when tried it on my current PC (64-bit) I had similar transition pixilating effects that I got with SH3proxy on lower resolutions. Maybe it's some compatibility conflict that hasn't been ironed out?

**Comment by JoesGuy** [comment] 2017-07-23 21:11
Unfortunately I haven't the opportunity to test it on a 32-bit OS.

**Comment by seagull** [comment] 2017-07-23 21:25
I don't know what transitions drifting across the screen has to do with tearing or transition pixellation.

**Comment by TaiNoBouken** [comment] 2017-07-25 13:01
The transition pixilation seems to happen to me on lower resolutions with sh3proxy, the higher the resolution it goes from transition pixilation to transition drifiting, i.e. 1280 x 1024 transitions are pixilated. 1080p has drifting transitions. Sh3proxy seems to have the same screen tearing fix as D3DOverrider, like I said in my last comment -- when I use D3DOverrider on 64-bit it has a similar transition problem. My thinking is that the screen tearing fix that both programs may share, might be the reason for this transition problem.

**Comment by seagull** [comment] 2017-07-25 13:05
Oh, that makes sense.
I've been using the SH3 Widescreen fix for the last few weeks, that has a
fix for this included.
People reading this might want to migrate since development of this fix
seems to be moribund, if not dead outright.

**Comment by 07151129** [comment] 2017-07-25 15:20
I could never reproduce the issue myself, so I didn't fix it when I had time to. Since PixelationFix from WidescreenFixesPack reportedly fixes the issue, I will integrate it into sh3proxy this week.

**Comment by seagull** [comment] 2017-07-25 15:24
Oh my. Please accept my apologies.
Fitting that this would happen when discussing Silent Hill.

**Comment by JoesGuy** [comment] 2017-07-28 08:42
I wonder how the pixelation fix actually addresses it. Furthermore, I'm not even sure how either problem exists in the first place. Is it a widescreen issue?

**Comment by 07151129** [comment] 2017-07-31 15:32
Should be fixed in 0.9 (reopen this issues otherwise).

**Closed as completed by 07151129** 2017-07-31 15:32 UTC
