### ISSUE TITLE
Gamma Correction

### ISSUE THREAD

**Issue by CHNSK** [07151129/sh3proxy#6] opened 2016-08-16 12:57 UTC
When I try to adjust gamma images get corrupted:
http://imgur.com/a/eH70z
http://imgur.com/a/hlF98
http://imgur.com/a/m5vOS

I thought you might want to know.

**Comment by 07151129** [comment] 2016-08-17 09:59
I can reproduce this, seems to be caused by our video patches. I'll have a look.

**Comment by 07151129** [comment] 2016-08-17 12:37
Fixed in next release.

**Closed as completed by 07151129** 2016-08-17 12:37 UTC
